### ISSUE TITLE
Probleme mit python und der crontab

### ISSUE THREAD

**Issue by hardtech87** [vinc3PO/ebayKleinanzeigenAlert#21]
Hi.

ich versuche schon einige stunden das ganz zum laufen zu bringen, aber ohne Erfolg.
wenn ich genau nach anleitung gehe, ist beim befehl python -m ebAlert schluss. da kommt eine Fehlermeldung. Diese konnte ich gestern nach viel probieren durch "python3" umgehen. Dann wird gezeigt, das man nur noch ebAlert eingibt ohne" python -m". Das geht bei mir nicht mehr. wenn ich die komplette Zeile schreibe, kann ich zumindest dann einen Link erstellen und der wird auch einmal ausgelesen. aber dann gehts wieder im crontab nicht weiter. das läuft einfach nicht.

pi@raspberrypi:~/ebayKleinanzeigenAlert $ ebAlert
Traceback (most recent call last):
  File "/home/pi/.local/bin/ebAlert", line 6, in <module>
    from ebAlert.main import cli
  File "/home/pi/.local/lib/python2.7/site-packages/ebAlert/__init__.py", line 2, in <module>
    from ebAlert.core.config import settings
  File "/home/pi/.local/lib/python2.7/site-packages/ebAlert/core/config.py", line 9
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
                                                                                                           ^
SyntaxError: invalid syntax

meine Bashrc sieht so aus

export  PATH="/home/pi/.local/bin:$PATH"
alias python3=python3.7

crontba
*/1 1-24 * * * /usr/bin/python3 /home/pi/ebayKleinanzeigenAlert/python3 -m ebAlert start > /home/$

**Comment by hardtech87** [comment]
so das mit dem python hab ich gelöst. ich halte ne alte pip version. und nachdem ich die aktualisiert habe musste ich erneut pip install . ausführen. jetzt läuft es bis auf die crontab .
er erstellt eine datei aber es steht nix drin

**Comment by daniel22-git** [comment]
> TELEGRAM_API_URL = f"[https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&](https://api.telegram.org/bot%7BTOKEN%7D/sendMessage?chat_id=%7BCHAT_ID%7D&parse_mode=HTML&)"""
> ^
> SyntaxError: invalid syntax

Schau Mal, das sieht für mich so aus als hättest du einen Fehler beim reinkopieren deiner ChatID oder TelegramToken gemacht. Beispielsweise ein " zu viel oder sowas.

**Comment by hardtech87** [comment]
der Fehler kommt nur weil mein python und pip nicht zusammen passten. jetz läuft alles wunderbar. wenn ich ebAlert manuell starte, bekomm ich sogar angebote aufs handy. aber nicht per crontab, es wird nur die datei erstellt aber die ist leer

**Comment by daniel22-git** [comment]
> */1 1-24 * * * /usr/bin/python3 /home/pi/ebayKleinanzeigenAlert/python3 -m ebAlert start > /home/$

Das ist aufjedenfall falsch, das siehst du wenn du es unabhängig vom Crontab in die Kommandozeile eingeben würdest. Versuch stattdessen mal folgendes: `/usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start` unabhängig vom Crontab erstmal.

Wenn das nicht klappt: `/usr/bin/python3 /home/pi/ebayKleinanzeigenAlert/ebAlert start`

**Comment by hardtech87** [comment]
geht beides nicht

**Comment by daniel22-git** [comment]
![Screenshot_20221212-162040_JuiceSSH](https://user-images.githubusercontent.com/43549788/207083237-75c0e1ed-3b27-48b5-bb69-cb40028186f3.png)

Welche Fehlermeldung kommt denn bei dir?

**Comment by hardtech87** [comment]
ne geht nicht.
wenn ich in den Ordner EbayKleinanzeigenAlert wechsel und nur ebAlert eingebe, geht es. sogar im root Verzeichnis kann ich das eingeben und es geht.
aber so alles zusammen nicht.
bei which python kommt
/usr/bin/python

**Comment by hardtech87** [comment]
pi@raspberrypi:~ $ /usr/bin/python3 /home/pi/ebayKleinanzeigenAlert/ebAlert start
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/ebayKleinanzeigenAlert/ebAlert/__main__.py", line 1, in <module>
    from ebAlert import main
ModuleNotFoundError: No module named 'ebAlert'

**Comment by hardtech87** [comment]
pi@raspberrypi:~ $ /usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/ebayKleinanzeigenAlert/ebAlert/__main__.py", line 1, in <module>
    from ebAlert import main
  File "/home/pi/.local/lib/python2.7/site-packages/ebAlert/__init__.py", line 2, in <module>
    from ebAlert.core.config import settings
  File "/home/pi/.local/lib/python2.7/site-packages/ebAlert/core/config.py", line 9
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
                                                                                                           ^
SyntaxError: invalid syntax

**Comment by daniel22-git** [comment]
Ich glaube du hast es irgendwie doppelt bei dir installiert. Die Version welche er im Path hat ist die fehlerhafte.

Theoretisch sollte dieser crontab bei dir klappen.
`*/5 6-23 * * * python -m ebAlert start > /home/pi/out.txt`

**Comment by hardtech87** [comment]
nur eine Datei ohne Inhalt
ich gebs gleich auf

**Comment by hardtech87** [comment]
TELEGRAM_API_URL = f"[https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&](https://api.telegram.org/bot%7BTOKEN%7D/sendMessage?chat_id=%7BCHAT_ID%7D&parse_mode=HTML&)"""

sollen diese 3 " dahinten stehen? habe 2 weg gemacht aber der aktualisiert das nicht

**Comment by daniel22-git** [comment]
> TELEGRAM_API_URL = f"[https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&](https://api.telegram.org/bot%7BTOKEN%7D/sendMessage?chat_id=%7BCHAT_ID%7D&parse_mode=HTML&)"""
> 
> sollen diese 3 " dahinten stehen? habe 2 weg gemacht aber der aktualisiert das nicht

Wie schon oben beschrieben, könntest du in deiner config Datei einen Fehler gemacht haben. Sobald du diesen behoben hast musst du `pip install .` erneut ausführen damit er übernommen wird.

**Comment by hardtech87** [comment]
ahhh ok


ok ändert nichts
 werde noch einmal alles neu aufsetzen und ein letztes mal probieren.
auf jedenfall muss ich voher pip aktualisieren sonst geht alles wieder nicht

**Comment by daniel22-git** [comment]
> ahhh ok

So muss sie aussehen: (habe meine Daten anonymisiert)

```
import os
import logging


class Settings:
    TOKEN = os.environ.get("TOKEN") or "5xxxxxxx120:AAxxxxxxxxTE"
    CHAT_ID = os.environ.get("CHAT_ID") or "2xxxxxxx5"
    FILE_LOCATION = os.path.join(os.path.expanduser("~"), "ebayklein.db")
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
    LOGGING = os.environ.get("LOGGING") or logging.ERROR
    URL_BASE = "https://www.ebay-kleinanzeigen.de"


settings = Settings()
```

**Comment by daniel22-git** [comment]
> ahhh ok
> 
> ok ändert nichts werde noch einmal alles neu aufsetzen und ein letztes mal probieren. auf jedenfall muss ich voher pip aktualisieren sonst geht alles wieder nicht

Ansonsten gib doch mal `pip list` ein, wenn da ebayAlert ist, dann `pip uninstall ebayAlert` und dann wieder installieren mit `pip install .`

**Comment by hardtech87** [comment]
sieht genau gleich aus

import os
import logging


class Settings:
    TOKEN = os.environ.get("TOKEN") or "5xxxx9:Axxxxxxxhg"
    CHAT_ID = os.environ.get("CHAT_ID") or "5xxxxxxx7"
    FILE_LOCATION = os.path.join(os.path.expanduser("~"), "ebayklein.db")
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
    LOGGING = os.environ.get("LOGGING") or logging.ERROR
    URL_BASE = "https://www.ebay-kleinanzeigen.de"


settings = Settings()

**Comment by hardtech87** [comment]
Ansonsten gib doch mal pip list ein, wenn da ebayAlert ist, dann pip uninstall ebayAlert und dann wieder installieren mit pip install .

aber im ebayKleinanzeigenAlert ordner?

**Comment by daniel22-git** [comment]
Genau, wie im Video.

**Comment by hardtech87** [comment]
Requirement already satisfied: soupsieve>1.2 in /home/pi/.local/lib/python3.8/site-packages (from beautifulsoup4->bs4>=0.0.1->ebayAlert==1.3) (2.3.2.post1)
Installing collected packages: ebayAlert
  DEPRECATION: ebayAlert is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for ebayAlert ... done
Successfully installed ebayAlert-1.3

**Comment by dandud100** [comment]
> Successfully installed ebayAlert-1.3

Schaut doch schonmal gut aus.

**Comment by hardtech87** [comment]
pi@raspberrypi:~/ebayKleinanzeigenAlert $ /usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/ebayKleinanzeigenAlert/ebAlert/__main__.py", line 1, in <module>
    from ebAlert import main
  File "/home/pi/.local/lib/python2.7/site-packages/ebAlert/__init__.py", line 2, in <module>
    from ebAlert.core.config import settings
  File "/home/pi/.local/lib/python2.7/site-packages/ebAlert/core/config.py", line 9
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
                                                                                                           ^
SyntaxError: invalid syntax

**Comment by hardtech87** [comment]
nur ebAlert funktioniert wieder

**Comment by daniel22-git** [comment]
Jo, wie befürchtet hast du ebAlert doppelt installiert. Einmal für python2.7 mit fehler in der config und einmal funktionierend auf python3.8

Mach Mal `sudo nano /lib/python2.7/site-packages/ebAlert/core/config.py` siehst du dort die config Datei?

**Comment by hardtech87** [comment]
reparierbar? oder neu aufsetzen

verzeichnis existiert nicht

**Comment by daniel22-git** [comment]
> reparierbar? oder neu aufsetzen
> 
> verzeichnis existiert nicht

Können es versuchen. `pip3.6 uninstall ebayAlert`

**Comment by hardtech87** [comment]
pi@raspberrypi:~/ebayKleinanzeigenAlert $ pip3 uninstall ebayAlert
Found existing installation: ebayAlert 1.3
Uninstalling ebayAlert-1.3:
  Would remove:
    /home/pi/.local/bin/ebAlert
    /home/pi/.local/lib/python3.8/site-packages/ebAlert/*
    /home/pi/.local/lib/python3.8/site-packages/ebayAlert-1.3-py3.8.egg-info
Proceed (Y/n)? y
  Successfully uninstalled ebayAlert-1.3

**Comment by daniel22-git** [comment]
Sehr gut. Jetzt `pip uninstall ebayAlert`

Dann schauen ob ebayAlert weg ist: `python3 -m pip list` und `python -m pip list`

Wenn das dann erfolgt ist `pip install .` wie gewohnt.

**Comment by hardtech87** [comment]
pi@raspberrypi:~ $ pip uninstall ebayAlert
WARNING: Skipping ebayAlert as it is not installed.

**Comment by hardtech87** [comment]
bei python -m pip list ist es noch da

**Comment by daniel22-git** [comment]
Das ist schlecht, das muss noch raus. Das wird die fehlerhafte Installation sein.

**Comment by hardtech87** [comment]
geht nicht zu löschen

**Comment by daniel22-git** [comment]
> geht nicht zu löschen

Dann müssen wir das manuell versuchen. Kannst du über FTP oder über die Console schauen ob unter /lib/python2.7/site-packages/ was drin ist?

`pip show ebayAlert` sollte dir den Pfad aufjedenfall geben.

**Comment by hardtech87** [comment]
probier ich dann gleich , muss kurz mein sohn holen. ich melde mich.

ansonsten habe ich es aber wie beschrieben installiert, versteh nicht warum das so komisch ist

**Comment by hardtech87** [comment]
pi@raspberrypi:~ $ pip show ebayAlert
WARNING: Package(s) not found: ebayAlert

**Comment by hardtech87** [comment]
<img width="257" alt="Unbenannt" src="https://user-images.githubusercontent.com/28910202/207097894-45363bae-663d-4016-9542-f5425efce867.PNG">

**Comment by daniel22-git** [comment]
> pi@raspberrypi:~ $ pip show ebayAlert WARNING: Package(s) not found: ebayAlert

Okay, das macht für mich jetzt auch keinen sinn mehr, du meintest doch es wäre bei `pip list` noch da. 🤔

Ah, das Bild hätte vor deinem Text sein müssen. Ja dann passt es doch und du könntest es mit `pip install .` wieder installieren.

**Comment by daniel22-git** [comment]
> <img alt="Unbenannt" width="257" src="https://user-images.githubusercontent.com/28910202/207097894-45363bae-663d-4016-9542-f5425efce867.PNG">

Hier löschst du die beiden Ordner mit ebAlert.

**Comment by hardtech87** [comment]
habs gelöscht und dann im ebayKleinanzeigenAlert verzeichnis mit pip install . installiert.

jetzt zeigt mir python -m pip list und pyhton3 -m pip list einen ebayAlert ordner.

und bei
pi@raspberrypi:~/ebayKleinanzeigenAlert $ pip show ebayAlert
Name: ebayAlert
Version: 1.3
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/pi/.local/lib/python3.8/site-packages
Requires: bs4, click, requests, sqlalchemy
Required-by:

und bei 
pi@raspberrypi:~/ebayKleinanzeigenAlert $ pip3 show ebayAlert
Name: ebayAlert
Version: 1.3
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/pi/.local/lib/python3.8/site-packages
Requires: bs4, click, requests, sqlalchemy
Required-by:

also beide bei python3.8

**Comment by hardtech87** [comment]
pi@raspberrypi:~/ebayKleinanzeigenAlert $ python -m ebAlert
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "ebAlert/__init__.py", line 2, in <module>
    from ebAlert.core.config import settings
  File "ebAlert/core/config.py", line 9
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
                                                                                                           ^
SyntaxError: invalid syntax

pi@raspberrypi:~/ebayKleinanzeigenAlert $ python3 -m ebAlert
Usage: python -m ebAlert [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  links  Add/Show/Remove URL from database.
  start  Fetch new post and send telegramclass notification.

**Comment by dandud100** [comment]
Bezüglich pip show, das sieht gut aus, so ist es bei mir auch.

Aber nach wie vor ist deine config.py falsch.
Vermutlich ein unsichtbares Zeichen was sich eingeschlichen hat. Ich bin mir sicher sobald der Fehler in der config.py behoben ist und du anschließend wieder `pip install .` zum übernehmen ausführst läuft es.

**Comment by dandud100** [comment]
> > ahhh ok
> 
> So muss sie aussehen: (habe meine Daten anonymisiert)
> 
> ```
> import os
> import logging
> 
> 
> class Settings:
>     TOKEN = os.environ.get("TOKEN") or "5xxxxxxx120:AAxxxxxxxxTE"
>     CHAT_ID = os.environ.get("CHAT_ID") or "2xxxxxxx5"
>     FILE_LOCATION = os.path.join(os.path.expanduser("~"), "ebayklein.db")
>     TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
>     LOGGING = os.environ.get("LOGGING") or logging.ERROR
>     URL_BASE = "https://www.ebay-kleinanzeigen.de"
> 
> 
> settings = Settings()
> ```

Kopier doch Mal den Inhalt hier heraus und schreibe dann deinen Token und die Chat ID rein.

**Comment by daniel22-git** [comment]
> File "/usr/lib/python2.7/runpy.py"

Ich verstehe nicht warum da immernoch was mit Python2.7 ist.

**Comment by daniel22-git** [comment]
Vielleicht ist es doch das beste du lädst dir das aktuelle Raspbian Lite Image runter und versuchst es von Grund auf nochmal. Bevor du startest dann halt direkt `apt-get update` und `apt-get upgrade`. Wenn es dann immernoch nicht klappt dann mache ich dir ein fertiges Image wenn du willst.

**Comment by hardtech87** [comment]
das problem über das image läuft mein komplettes terrarium. und ich hab nur ein backup davon. das spiele ich immer ein um neu anzufangen. habe diesmal sogar update und upgrade gemacht, hab aber das gefühl das es das noch schlimmer macht.

der config code muss richtig sein, er funktioniert ja wenn ich es manuell starte

**Comment by daniel22-git** [comment]
Geht denn mittlerweile eines hiervon?

`/usr/bin/python /home/pi/ebayKleinanzeigenAlert/ebAlert start`

`/usr/bin/python3 /home/pi/ebayKleinanzeigenAlert/ebAlert start`

**Comment by hardtech87** [comment]
nein

**Comment by daniel22-git** [comment]
> nein

Dann weiß ich gerade nicht wie ich dir aus der Ferne noch helfen soll. Vielleicht weiß der Entwickler von dem Bot was hier der Fehler ist.

@vinc3PO can you help here?

**Comment by daniel22-git** [comment]
> das problem über das image läuft mein komplettes terrarium. und ich hab nur ein backup davon. das spiele ich immer ein um neu anzufangen. habe diesmal sogar update und upgrade gemacht, hab aber das gefühl das es das noch schlimmer macht.
> 

Hast du denn eine zweite MicroSD Karte rumliegen um das auszuprobieren?

**Comment by hardtech87** [comment]
Ich danke dir unheimlich für deine Mühen.

Es läuft. ich habe das Backup neu aufgespielt und von vorn begonnen und habe diesmal mit "pip3 install ." installiert. und die 3 hats gebracht, dadurch hat er es nicht bei python 2 und 3 rein installiert.
Vielen Vielen Dank

**Comment by hardtech87** [comment]
Eine Frage hab ich noch, in der out.txt steht nur einmal start der link und finish. is das korrekt oder muss jede suche da drin stehen?

**Comment by daniel22-git** [comment]
> Eine Frage hab ich noch, in der out.txt steht nur einmal start der link und finish. is das korrekt oder muss jede suche da drin stehen?

Ja, das ist richtig so. Schön, dass es nun funktioniert! 🎉
