### ISSUE TITLE
ebAlert neben Homebridge installieren

### ISSUE THREAD

**Issue by DanielZ3108** [vinc3PO/ebayKleinanzeigenAlert#23]
Hallo zusammen, ich hab den ebAlert bisher auf einem RasPi 3 laufen auf dem nichts anderes installiert ist.
Nun wollte ich den ebAlert aber auf dem Pi 4 neben meiner Homebridge für SmartHome installieren, bekomme es dort aber nicht zum laufen.

Bei `pip install .` kommt folgende Meldung. Danach läuft die Installation aber erfolgreich durch:

pi@homebridge:~/ebayKleinanzeigenAlert $ pip install .
The directory '/home/pi/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pi/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Mit dem Befehl `Python -m ebAlert`scheitert es dann leider komplett:

pi@homebridge:~/ebayKleinanzeigenAlert $ python -m ebAlert
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "ebAlert/__init__.py", line 2, in <module>
    from ebAlert.core.config import settings
  File "ebAlert/core/config.py", line 9
    TELEGRAM_API_URL = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&parse_mode=HTML&"""
                                                                                                           ^
SyntaxError: invalid syntax

Config-Datei ist richtig, läuft ja auf dem anderen Pi 3 auch ohne Probleme.
Auf dem Pi 4 läuft wie gesagt Homebridge, aber das sollte doch trotzdem machbar sein?

Gruß,
Daniel

**Comment by cyberpete2244** [comment]
Hallo. Du musst sicherstellen, dass du auf deinem neuen Raspberry python3
benutzt. Das Projekt nutzt Version 3 und zwischen zwei und drei gibt es
keine Abwärtskompatibilität. Ich gehe davon aus, dass auf deinem Raspberry
beide Python Versionen installiert sind, sowohl zwei als auch drei, und
daher musst du bei den Aufrufen von pip und dem Projekt als solches
explizit die Befehle für python3 verwenden.

Gruß Peter

DanielZ3108 ***@***.***> schrieb am Sa., 7. Jan. 2023, 13:33:

**Comment by DanielZ3108** [comment]
> Ich gehe davon aus, dass auf deinem Raspberry beide Python Versionen installiert sind, sowohl zwei als auch drei, und daher musst du bei den Aufrufen von pip und dem Projekt als solches explizit die Befehle für python3 verwenden. Gruß Peter 
> […](#)

Hallo Peter,
mit `python3 -m ebAlert` meldet er folgendes:

pi@homebridge:~/ebayKleinanzeigenAlert $ python3 -m ebAlert
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/ebayKleinanzeigenAlert/ebAlert/__main__.py", line 1, in <module>
    from ebAlert import main
  File "/home/pi/ebayKleinanzeigenAlert/ebAlert/main.py", line 5, in <module>
    from sqlalchemy.orm import Session
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by raphi3347** [comment]
> > Ich gehe davon aus, dass auf deinem Raspberry beide Python Versionen installiert sind, sowohl zwei als auch drei, und daher musst du bei den Aufrufen von pip und dem Projekt als solches explizit die Befehle für python3 verwenden. Gruß Peter
> > […](#)
> 
> Hallo Peter, mit `python3 -m ebAlert` meldet er folgendes:
> 
> pi@homebridge:~/ebayKleinanzeigenAlert $ python3 -m ebAlert Traceback (most recent call last): File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/usr/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/pi/ebayKleinanzeigenAlert/ebAlert/**main**.py", line 1, in from ebAlert import main File "/home/pi/ebayKleinanzeigenAlert/ebAlert/main.py", line 5, in from sqlalchemy.orm import Session ModuleNotFoundError: No module named 'sqlalchemy'

Hey Daniel, habe den selben Error _ModuleNotFoundError: No module named 'sqlalchemy'_
Hast du eine Lösung finden können? :)

**Comment by DanielZ3108** [comment]
Hey @raphi3347,

nein leider nicht. Hab den ebAlert nun auf einem eigenen Raspberry installiert, ist aber eigentlich quatsch, wenn der andere sowieso läuft. Bekomm es aber neben der Homebridge einfach nicht zum laufen.

**Comment by raphi3347** [comment]
> Hey @raphi3347,
> 
> nein leider nicht. Hab den ebAlert nun auf einem eigenen Raspberry installiert, ist aber eigentlich quatsch, wenn der andere sowieso läuft. Bekomm es aber neben der Homebridge einfach nicht zum laufen.

Ich habe nach mehreren Stunden jetzt tatsächlich endlich die Lösung des Problems gefunden ^^

Schau mal unter /home/DEINUSER/.local/lib, ob dort mehrere python Versionen installiert sind. Bei mir waren nur unter einer der beiden Versionen dort meine Module installiert. Eben auch sqlalchemy. Wenn du nur _python3 -m ebAlert_ eingibst, verwendet er scheinbar nicht automatisch die Python version, mit den richtigen Modulen. (Ich hatte dort nur zwei Ordner, in der zweiten python version war kein einziges module installiert. Kein Wunder wieso er das Module nicht gefunden hatte ...)

**_python3.10 -m ebAlert_** hat somit bei mir funktioniet, da unter dieser 3.10 Version alles installiert war. Ohne die Endung .10 hat er scheinbar immer nur auf den leeren Ordner zugegriffen.

**Comment by DanielZ3108** [comment]
Wie sehe ich denn ob mehrere Versionen installiert sind? Navigation in den Ordner und dann?

**Comment by raphi3347** [comment]
> Wie sehe ich denn ob mehrere Versionen installiert sind? Navigation in den Ordner und dann?

Du kannst im terminal python3 oder nur python eingeben, dort siehst du welche version als Main erkannt wird, die dann auch deine python Befehle ausführt. Das war bei mir 3.11.2 der latest release und wenn du dann mal in den Python Ordnern unter home/DEINUSERNAME/.local/lib nachsiehst, such die version bei der unter dem Ordner _site-packages_ sqlalchemy zu finden ist.

**Comment by DanielZ3108** [comment]
2.7.16 & 3.7.3
Funktioniert aber beides leider nicht

**Comment by raphi3347** [comment]
> 2.7.16 & 3.7.3 Funktioniert aber beides leider nicht

Selber Error?

Hast du geschaut, in welcher Version das benötigte Modul installiert ist? Und dementsprechend _python2.7.16 -m ebAlert_ oder _python3.7.3 -m ebAlert_ ausgeführt? So hat's bei mir geklappt.

**Comment by DanielZ3108** [comment]
Leider weiß ich nicht wie ich nachschauen kann in welcher Version das benötigte Modul installiert ist. Ich nutze am Mac das Terminal mit ssh. Mit einer Verzeichnisstruktur wäre das wohl einfacher.
Aber python2.7.16 -m ebAlert oder python3.7.3 -m ebAlert funktioniert beides nicht.

-bash: python2.7.16: Kommando nicht gefunden.
-bash: python3.7.3: Kommando nicht gefunden.
