### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by raphi3347** [vinc3PO/ebayKleinanzeigenAlert#29]
**_Hey, cooles Tool!_**

Hab nur ein Problem, welches sich irgendwie nicht lösen lässt. Nachdem ich python -m ebAlert ausführe, bekomme ich ständig folgende Fehlermeldung:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/linuxmint/ebayKleinanzeigenAlert/ebAlert/__main__.py", line 1, in <module>
    from ebAlert import main
  File "/home/linuxmint/ebayKleinanzeigenAlert/ebAlert/main.py", line 5, in <module>
    from sqlalchemy.orm import Session
ModuleNotFoundError: No module named 'sqlalchemy'
`
sqlalchemy 1.4 als auch unter der latest release
Python 3.11.2
Linux mint

**Comment by raphi3347** [comment]
**_Copy paste aus meinem anderen Post:_**

Ich habe nach mehreren Stunden jetzt tatsächlich endlich die Lösung des Problems gefunden ^^

Schau mal unter /home/DEINUSER/.local/lib, ob dort mehrere python Versionen installiert sind. Bei mir waren nur unter einer der beiden Versionen dort meine Module installiert. Eben auch sqlalchemy. Wenn du nur python3 -m ebAlert eingibst, verwendet er scheinbar nicht automatisch die Python version, mit den richtigen Modulen. (Ich hatte dort nur zwei Ordner, in der zweiten python version war kein einziges module installiert. Kein Wunder wieso er das Module nicht gefunden hatte ...)

python3.10 -m ebAlert hat somit bei mir funktioniet, da unter dieser 3.10 Version alles installiert war. Ohne die Endung .10 hat er scheinbar immer nur auf den leeren Ordner zugegriffen._
