### ISSUE TITLE
a Bug while adding a certain URL

### ISSUE THREAD

**Issue by mhumhu** [vinc3PO/ebayKleinanzeigenAlert#7]
mhu@pihole:~$ ebAlert links -a https://www.ebay-kleinanzeigen.de/s-atari/k0
Traceback (most recent call last):
  File "/home/mhu/.local/bin/ebAlert", line 8, in <module>
    sys.exit(cli())
  File "/home/mhu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mhu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mhu/.local/lib/python3.8/site-packages/ebAlert/main.py", line 62, in links
    add_post(add)
  File "/home/mhu/.local/lib/python3.8/site-packages/ebAlert/main.py", line 79, in add_post
    for post in ebayclass.get_post(link):
  File "/home/mhu/.local/lib/python3.8/site-packages/ebAlert/ebayscrapping/ebayclass.py", line 48, in get_post
    items = [EbayItem(item) for item in articles]
  File "/home/mhu/.local/lib/python3.8/site-packages/ebAlert/ebayscrapping/ebayclass.py", line 48, in <listcomp>
    items = [EbayItem(item) for item in articles]
  File "/home/mhu/.local/lib/python3.8/site-packages/ebAlert/ebayscrapping/ebayclass.py", line 14, in __init__
    self.title = contents.find("a", {"class": "ellipsis"}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by vinc3PO** [comment]
Hi,
Thank you for letting me know. It appeared that there was some error while parsing the website.
I was not able to repeat the error.  
I have added some error handling, so if there is a failing article it skip to the next one. 
Let me know if you find more problems. 
Good luck with the retro gaming.

**Comment by vinc3PO** [comment]
Look like the issue is bigger than anticipated. 
I'll look at it asap
